Remove yaml code which caused Union bug
For some reason, the method removed in this commit would cause

SystemStackError: stack level too deep
from /Users/michaelappell/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/psych/visitors/yaml_tree.rb:70:in `new'

errors whenever saving a new Event. Very odd.